# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_post_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(default='不願意透漏身份的人', max_length=10),
        ),
    ]
